### ISSUE TITLE
Should we use Twitter API to get users's ID instead fo this hardcoded ID?

### ISSUE THREAD

**Issue by cuducos** [zehfernandes/twitter-following-map-obsidian#2]
https://github.com/zehfernandes/twitter-following-map-obsidian/blob/9723efb2dd4329a74c78dfcb3c40168161c1b347/index.js#L41

**Comment by zehfernandes** [comment]
Nice catch. Yes! Already made a change to fix it.

Thanks 🙌

**Comment by cuducos** [comment]
Excellent ✨
